using DecayEngine.ModuleSDK.Object.Input;
using DecayEngine.ModuleSDK.Object.Input.Triggers.GamePad;
using DecayEngine.ModuleSDK.Object.Input.Triggers.Keyboard;
using DecayEngine.SDL2.Native.Sdl2Interop;

namespace DecayEngine.SDL2.Native.Input
{
    public static class Sdl2ScanCodeParser
    {
        public static KeyboardScanCode ParseKey(SDL.SDL_Scancode scanCode)
        {
            return scanCode switch
            {
                SDL.SDL_Scancode.SDL_SCANCODE_A => KeyboardScanCode.A,
                SDL.SDL_Scancode.SDL_SCANCODE_B => KeyboardScanCode.B,
                SDL.SDL_Scancode.SDL_SCANCODE_C => KeyboardScanCode.C,
                SDL.SDL_Scancode.SDL_SCANCODE_D => KeyboardScanCode.D,
                SDL.SDL_Scancode.SDL_SCANCODE_E => KeyboardScanCode.E,
                SDL.SDL_Scancode.SDL_SCANCODE_F => KeyboardScanCode.F,
                SDL.SDL_Scancode.SDL_SCANCODE_G => KeyboardScanCode.G,
                SDL.SDL_Scancode.SDL_SCANCODE_H => KeyboardScanCode.H,
                SDL.SDL_Scancode.SDL_SCANCODE_I => KeyboardScanCode.I,
                SDL.SDL_Scancode.SDL_SCANCODE_J => KeyboardScanCode.J,
                SDL.SDL_Scancode.SDL_SCANCODE_K => KeyboardScanCode.K,
                SDL.SDL_Scancode.SDL_SCANCODE_L => KeyboardScanCode.L,
                SDL.SDL_Scancode.SDL_SCANCODE_M => KeyboardScanCode.M,
                SDL.SDL_Scancode.SDL_SCANCODE_N => KeyboardScanCode.N,
                SDL.SDL_Scancode.SDL_SCANCODE_O => KeyboardScanCode.O,
                SDL.SDL_Scancode.SDL_SCANCODE_P => KeyboardScanCode.P,
                SDL.SDL_Scancode.SDL_SCANCODE_Q => KeyboardScanCode.Q,
                SDL.SDL_Scancode.SDL_SCANCODE_R => KeyboardScanCode.R,
                SDL.SDL_Scancode.SDL_SCANCODE_S => KeyboardScanCode.S,
                SDL.SDL_Scancode.SDL_SCANCODE_T => KeyboardScanCode.T,
                SDL.SDL_Scancode.SDL_SCANCODE_U => KeyboardScanCode.U,
                SDL.SDL_Scancode.SDL_SCANCODE_V => KeyboardScanCode.V,
                SDL.SDL_Scancode.SDL_SCANCODE_W => KeyboardScanCode.W,
                SDL.SDL_Scancode.SDL_SCANCODE_X => KeyboardScanCode.X,
                SDL.SDL_Scancode.SDL_SCANCODE_Y => KeyboardScanCode.Y,
                SDL.SDL_Scancode.SDL_SCANCODE_Z => KeyboardScanCode.Z,
                SDL.SDL_Scancode.SDL_SCANCODE_1 => KeyboardScanCode.Alpha1,
                SDL.SDL_Scancode.SDL_SCANCODE_2 => KeyboardScanCode.Alpha2,
                SDL.SDL_Scancode.SDL_SCANCODE_3 => KeyboardScanCode.Alpha3,
                SDL.SDL_Scancode.SDL_SCANCODE_4 => KeyboardScanCode.Alpha4,
                SDL.SDL_Scancode.SDL_SCANCODE_5 => KeyboardScanCode.Alpha5,
                SDL.SDL_Scancode.SDL_SCANCODE_6 => KeyboardScanCode.Alpha6,
                SDL.SDL_Scancode.SDL_SCANCODE_7 => KeyboardScanCode.Alpha7,
                SDL.SDL_Scancode.SDL_SCANCODE_8 => KeyboardScanCode.Alpha8,
                SDL.SDL_Scancode.SDL_SCANCODE_9 => KeyboardScanCode.Alpha9,
                SDL.SDL_Scancode.SDL_SCANCODE_0 => KeyboardScanCode.Alpha0,
                SDL.SDL_Scancode.SDL_SCANCODE_RETURN => KeyboardScanCode.Return,
                SDL.SDL_Scancode.SDL_SCANCODE_ESCAPE => KeyboardScanCode.Escape,
                SDL.SDL_Scancode.SDL_SCANCODE_BACKSPACE => KeyboardScanCode.Backspace,
                SDL.SDL_Scancode.SDL_SCANCODE_TAB => KeyboardScanCode.Tab,
                SDL.SDL_Scancode.SDL_SCANCODE_SPACE => KeyboardScanCode.Space,
                SDL.SDL_Scancode.SDL_SCANCODE_MINUS => KeyboardScanCode.Minus,
                SDL.SDL_Scancode.SDL_SCANCODE_EQUALS => KeyboardScanCode.EqualsKey,
                SDL.SDL_Scancode.SDL_SCANCODE_LEFTBRACKET => KeyboardScanCode.LeftBracket,
                SDL.SDL_Scancode.SDL_SCANCODE_RIGHTBRACKET => KeyboardScanCode.RightBracket,
                SDL.SDL_Scancode.SDL_SCANCODE_BACKSLASH => KeyboardScanCode.Backslash,
                SDL.SDL_Scancode.SDL_SCANCODE_NONUSHASH => KeyboardScanCode.InternationalHash,
                SDL.SDL_Scancode.SDL_SCANCODE_SEMICOLON => KeyboardScanCode.Semicolon,
                SDL.SDL_Scancode.SDL_SCANCODE_APOSTROPHE => KeyboardScanCode.Apostrophe,
                SDL.SDL_Scancode.SDL_SCANCODE_GRAVE => KeyboardScanCode.Grave,
                SDL.SDL_Scancode.SDL_SCANCODE_COMMA => KeyboardScanCode.Comma,
                SDL.SDL_Scancode.SDL_SCANCODE_PERIOD => KeyboardScanCode.Period,
                SDL.SDL_Scancode.SDL_SCANCODE_SLASH => KeyboardScanCode.Slash,
                SDL.SDL_Scancode.SDL_SCANCODE_CAPSLOCK => KeyboardScanCode.Capslock,
                SDL.SDL_Scancode.SDL_SCANCODE_F1 => KeyboardScanCode.F1,
                SDL.SDL_Scancode.SDL_SCANCODE_F2 => KeyboardScanCode.F2,
                SDL.SDL_Scancode.SDL_SCANCODE_F3 => KeyboardScanCode.F3,
                SDL.SDL_Scancode.SDL_SCANCODE_F4 => KeyboardScanCode.F4,
                SDL.SDL_Scancode.SDL_SCANCODE_F5 => KeyboardScanCode.F5,
                SDL.SDL_Scancode.SDL_SCANCODE_F6 => KeyboardScanCode.F6,
                SDL.SDL_Scancode.SDL_SCANCODE_F7 => KeyboardScanCode.F7,
                SDL.SDL_Scancode.SDL_SCANCODE_F8 => KeyboardScanCode.F8,
                SDL.SDL_Scancode.SDL_SCANCODE_F9 => KeyboardScanCode.F9,
                SDL.SDL_Scancode.SDL_SCANCODE_F10 => KeyboardScanCode.F10,
                SDL.SDL_Scancode.SDL_SCANCODE_F11 => KeyboardScanCode.F11,
                SDL.SDL_Scancode.SDL_SCANCODE_F12 => KeyboardScanCode.F12,
                SDL.SDL_Scancode.SDL_SCANCODE_PRINTSCREEN => KeyboardScanCode.PrintScreen,
                SDL.SDL_Scancode.SDL_SCANCODE_SCROLLLOCK => KeyboardScanCode.ScrollLock,
                SDL.SDL_Scancode.SDL_SCANCODE_PAUSE => KeyboardScanCode.Pause,
                SDL.SDL_Scancode.SDL_SCANCODE_INSERT => KeyboardScanCode.Insert,
                SDL.SDL_Scancode.SDL_SCANCODE_HOME => KeyboardScanCode.Home,
                SDL.SDL_Scancode.SDL_SCANCODE_PAGEUP => KeyboardScanCode.PageUp,
                SDL.SDL_Scancode.SDL_SCANCODE_DELETE => KeyboardScanCode.Delete,
                SDL.SDL_Scancode.SDL_SCANCODE_END => KeyboardScanCode.End,
                SDL.SDL_Scancode.SDL_SCANCODE_PAGEDOWN => KeyboardScanCode.PageDown,
                SDL.SDL_Scancode.SDL_SCANCODE_RIGHT => KeyboardScanCode.ArrowRight,
                SDL.SDL_Scancode.SDL_SCANCODE_LEFT => KeyboardScanCode.ArrowLeft,
                SDL.SDL_Scancode.SDL_SCANCODE_DOWN => KeyboardScanCode.ArrowDown,
                SDL.SDL_Scancode.SDL_SCANCODE_UP => KeyboardScanCode.ArrowUp,
                SDL.SDL_Scancode.SDL_SCANCODE_NUMLOCKCLEAR => KeyboardScanCode.NumLock,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_DIVIDE => KeyboardScanCode.NumpadDiv,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY => KeyboardScanCode.NumpadMult,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_MINUS => KeyboardScanCode.NumpadMinus,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_PLUS => KeyboardScanCode.NumpadPlus,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_ENTER => KeyboardScanCode.NumpadEnter,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_1 => KeyboardScanCode.Numpad1,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_2 => KeyboardScanCode.Numpad2,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_3 => KeyboardScanCode.Numpad3,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_4 => KeyboardScanCode.Numpad4,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_5 => KeyboardScanCode.Numpad5,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_6 => KeyboardScanCode.Numpad6,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_7 => KeyboardScanCode.Numpad7,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_8 => KeyboardScanCode.Numpad8,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_9 => KeyboardScanCode.Numpad9,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_0 => KeyboardScanCode.Numpad0,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_PERIOD => KeyboardScanCode.NumpadPeriod,
                SDL.SDL_Scancode.SDL_SCANCODE_NONUSBACKSLASH => KeyboardScanCode.InternationalBackslash,
                SDL.SDL_Scancode.SDL_SCANCODE_APPLICATION => KeyboardScanCode.MediaApplication,
                SDL.SDL_Scancode.SDL_SCANCODE_POWER => KeyboardScanCode.MediaPower,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_EQUALS => KeyboardScanCode.NumpadEquals,
                SDL.SDL_Scancode.SDL_SCANCODE_F13 => KeyboardScanCode.F13,
                SDL.SDL_Scancode.SDL_SCANCODE_F14 => KeyboardScanCode.F14,
                SDL.SDL_Scancode.SDL_SCANCODE_F15 => KeyboardScanCode.F15,
                SDL.SDL_Scancode.SDL_SCANCODE_F16 => KeyboardScanCode.F16,
                SDL.SDL_Scancode.SDL_SCANCODE_F17 => KeyboardScanCode.F17,
                SDL.SDL_Scancode.SDL_SCANCODE_F18 => KeyboardScanCode.F18,
                SDL.SDL_Scancode.SDL_SCANCODE_F19 => KeyboardScanCode.F19,
                SDL.SDL_Scancode.SDL_SCANCODE_F20 => KeyboardScanCode.F20,
                SDL.SDL_Scancode.SDL_SCANCODE_F21 => KeyboardScanCode.F21,
                SDL.SDL_Scancode.SDL_SCANCODE_F22 => KeyboardScanCode.F22,
                SDL.SDL_Scancode.SDL_SCANCODE_F23 => KeyboardScanCode.F23,
                SDL.SDL_Scancode.SDL_SCANCODE_F24 => KeyboardScanCode.F24,
                SDL.SDL_Scancode.SDL_SCANCODE_EXECUTE => KeyboardScanCode.MediaExecute,
                SDL.SDL_Scancode.SDL_SCANCODE_HELP => KeyboardScanCode.MediaHelp,
                SDL.SDL_Scancode.SDL_SCANCODE_MENU => KeyboardScanCode.Menu,
                SDL.SDL_Scancode.SDL_SCANCODE_SELECT => KeyboardScanCode.MediaSelect,
                SDL.SDL_Scancode.SDL_SCANCODE_STOP => KeyboardScanCode.MediaStop,
                SDL.SDL_Scancode.SDL_SCANCODE_AGAIN => KeyboardScanCode.MediaAgain,
                SDL.SDL_Scancode.SDL_SCANCODE_UNDO => KeyboardScanCode.MediaUndo,
                SDL.SDL_Scancode.SDL_SCANCODE_CUT => KeyboardScanCode.MediaCut,
                SDL.SDL_Scancode.SDL_SCANCODE_COPY => KeyboardScanCode.MediaCopy,
                SDL.SDL_Scancode.SDL_SCANCODE_PASTE => KeyboardScanCode.MediaPaste,
                SDL.SDL_Scancode.SDL_SCANCODE_FIND => KeyboardScanCode.MediaFind,
                SDL.SDL_Scancode.SDL_SCANCODE_MUTE => KeyboardScanCode.MediaMute,
                SDL.SDL_Scancode.SDL_SCANCODE_VOLUMEUP => KeyboardScanCode.MediaVolumeUp,
                SDL.SDL_Scancode.SDL_SCANCODE_VOLUMEDOWN => KeyboardScanCode.MediaVolumeDown,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_COMMA => KeyboardScanCode.NumpadPeriod,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_EQUALSAS400 => KeyboardScanCode.NumpadEquals,
                SDL.SDL_Scancode.SDL_SCANCODE_INTERNATIONAL1 => KeyboardScanCode.International1,
                SDL.SDL_Scancode.SDL_SCANCODE_INTERNATIONAL2 => KeyboardScanCode.International2,
                SDL.SDL_Scancode.SDL_SCANCODE_INTERNATIONAL3 => KeyboardScanCode.International3,
                SDL.SDL_Scancode.SDL_SCANCODE_INTERNATIONAL4 => KeyboardScanCode.International4,
                SDL.SDL_Scancode.SDL_SCANCODE_INTERNATIONAL5 => KeyboardScanCode.International5,
                SDL.SDL_Scancode.SDL_SCANCODE_INTERNATIONAL6 => KeyboardScanCode.International6,
                SDL.SDL_Scancode.SDL_SCANCODE_INTERNATIONAL7 => KeyboardScanCode.International7,
                SDL.SDL_Scancode.SDL_SCANCODE_INTERNATIONAL8 => KeyboardScanCode.International8,
                SDL.SDL_Scancode.SDL_SCANCODE_INTERNATIONAL9 => KeyboardScanCode.International9,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_00 => KeyboardScanCode.Numpad0,
                SDL.SDL_Scancode.SDL_SCANCODE_KP_000 => KeyboardScanCode.Numpad0,
                SDL.SDL_Scancode.SDL_SCANCODE_THOUSANDSSEPARATOR => KeyboardScanCode.Colon,
                SDL.SDL_Scancode.SDL_SCANCODE_DECIMALSEPARATOR => KeyboardScanCode.Period,
                SDL.SDL_Scancode.SDL_SCANCODE_CURRENCYUNIT => KeyboardScanCode.CurrencySymbol,
                SDL.SDL_Scancode.SDL_SCANCODE_CURRENCYSUBUNIT => KeyboardScanCode.CurrencySubSymbol,
                SDL.SDL_Scancode.SDL_SCANCODE_LCTRL => KeyboardScanCode.LeftControl,
                SDL.SDL_Scancode.SDL_SCANCODE_LSHIFT => KeyboardScanCode.LeftShift,
                SDL.SDL_Scancode.SDL_SCANCODE_LALT => KeyboardScanCode.LeftAlt,
                SDL.SDL_Scancode.SDL_SCANCODE_LGUI => KeyboardScanCode.LeftOsKey,
                SDL.SDL_Scancode.SDL_SCANCODE_RCTRL => KeyboardScanCode.RightControl,
                SDL.SDL_Scancode.SDL_SCANCODE_RSHIFT => KeyboardScanCode.RightShift,
                SDL.SDL_Scancode.SDL_SCANCODE_RALT => KeyboardScanCode.RightAlt,
                SDL.SDL_Scancode.SDL_SCANCODE_RGUI => KeyboardScanCode.RightOsKey,
                SDL.SDL_Scancode.SDL_SCANCODE_MODE => KeyboardScanCode.Mode,
                SDL.SDL_Scancode.SDL_SCANCODE_AUDIONEXT => KeyboardScanCode.MediaNext,
                SDL.SDL_Scancode.SDL_SCANCODE_AUDIOPREV => KeyboardScanCode.MediaPrev,
                SDL.SDL_Scancode.SDL_SCANCODE_AUDIOSTOP => KeyboardScanCode.MediaStop,
                SDL.SDL_Scancode.SDL_SCANCODE_AUDIOPLAY => KeyboardScanCode.MediaPlay,
                SDL.SDL_Scancode.SDL_SCANCODE_AUDIOMUTE => KeyboardScanCode.MediaMute,
                SDL.SDL_Scancode.SDL_SCANCODE_MEDIASELECT => KeyboardScanCode.MediaSelect,
                SDL.SDL_Scancode.SDL_SCANCODE_WWW => KeyboardScanCode.MediaWeb,
                SDL.SDL_Scancode.SDL_SCANCODE_MAIL => KeyboardScanCode.MediaMail,
                SDL.SDL_Scancode.SDL_SCANCODE_CALCULATOR => KeyboardScanCode.MediaCalculator,
                SDL.SDL_Scancode.SDL_SCANCODE_COMPUTER => KeyboardScanCode.MediaComputer,
                _ => KeyboardScanCode.Unsupported
            };
        }

        public static GamePadButtonScanCode ParseGamePadButton(SDL.SDL_GameControllerButton scanCode)
        {
            return scanCode switch
            {
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_A => GamePadButtonScanCode.A,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_B => GamePadButtonScanCode.B,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_X => GamePadButtonScanCode.X,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_Y => GamePadButtonScanCode.Y,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_BACK => GamePadButtonScanCode.Back,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_GUIDE => GamePadButtonScanCode.Guide,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_START => GamePadButtonScanCode.Start,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_LEFTSTICK => GamePadButtonScanCode.L3,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_RIGHTSTICK => GamePadButtonScanCode.R3,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_LEFTSHOULDER => GamePadButtonScanCode.L1,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_RIGHTSHOULDER => GamePadButtonScanCode.R1,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_UP => GamePadButtonScanCode.Up,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_DOWN => GamePadButtonScanCode.Down,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_LEFT => GamePadButtonScanCode.Left,
                SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_RIGHT => GamePadButtonScanCode.Right,
                _ => GamePadButtonScanCode.Unsupported
            };
        }

        public static GamePadAxisScanCode ParseGamePadAxis(SDL.SDL_GameControllerAxis scanCode)
        {
            return scanCode switch
            {
                SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_LEFTX => GamePadAxisScanCode.LeftX,
                SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_LEFTY => GamePadAxisScanCode.LeftY,
                SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_RIGHTX => GamePadAxisScanCode.RightX,
                SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_RIGHTY => GamePadAxisScanCode.RightY,
                SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_TRIGGERLEFT => GamePadAxisScanCode.L2,
                SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_TRIGGERRIGHT => GamePadAxisScanCode.R2,
                _ => GamePadAxisScanCode.Unsupported
            };
        }
    }
}