using DecayEngine.ModuleSDK.Exports.Attributes;

namespace DecayEngine.ModuleSDK.Object.Input.Triggers.Keyboard
{
    [ScriptExportEnum("KeyboardScanCode", "Represents the keys of a Keyboard.")]
    public enum KeyboardScanCode
    {
        [ScriptExportField("Unsupported key.")]
        Unsupported = 0,
        [ScriptExportField("To be documented.")]
        A = 1,
		[ScriptExportField("To be documented.")]
        B = 2,
		[ScriptExportField("To be documented.")]
        C = 3,
		[ScriptExportField("To be documented.")]
        D = 4,
		[ScriptExportField("To be documented.")]
        E = 5,
		[ScriptExportField("To be documented.")]
        F = 6,
		[ScriptExportField("To be documented.")]
        G = 7,
		[ScriptExportField("To be documented.")]
        H = 8,
		[ScriptExportField("To be documented.")]
        I = 9,
		[ScriptExportField("To be documented.")]
        J = 10,
		[ScriptExportField("To be documented.")]
        K = 11,
		[ScriptExportField("To be documented.")]
        L = 12,
		[ScriptExportField("To be documented.")]
        M = 13,
		[ScriptExportField("To be documented.")]
        N = 14,
		[ScriptExportField("To be documented.")]
        O = 15,
		[ScriptExportField("To be documented.")]
        P = 16,
		[ScriptExportField("To be documented.")]
        Q = 17,
		[ScriptExportField("To be documented.")]
        R = 18,
		[ScriptExportField("To be documented.")]
        S = 19,
		[ScriptExportField("To be documented.")]
        T = 20,
		[ScriptExportField("To be documented.")]
        U = 21,
		[ScriptExportField("To be documented.")]
        V = 22,
		[ScriptExportField("To be documented.")]
        W = 23,
		[ScriptExportField("To be documented.")]
        X = 24,
		[ScriptExportField("To be documented.")]
        Y = 25,
		[ScriptExportField("To be documented.")]
        Z = 26,
		[ScriptExportField("To be documented.")]
        Alpha0 = 27,
		[ScriptExportField("To be documented.")]
        Alpha1 = 28,
		[ScriptExportField("To be documented.")]
        Alpha2 = 29,
		[ScriptExportField("To be documented.")]
        Alpha3 = 30,
		[ScriptExportField("To be documented.")]
        Alpha4 = 31,
		[ScriptExportField("To be documented.")]
        Alpha5 = 32,
		[ScriptExportField("To be documented.")]
        Alpha6 = 33,
		[ScriptExportField("To be documented.")]
        Alpha7 = 34,
		[ScriptExportField("To be documented.")]
        Alpha8 = 35,
		[ScriptExportField("To be documented.")]
        Alpha9 = 36,
		[ScriptExportField("To be documented.")]
        Numpad0 = 37,
		[ScriptExportField("To be documented.")]
        Numpad1 = 38,
		[ScriptExportField("To be documented.")]
        Numpad2 = 39,
		[ScriptExportField("To be documented.")]
        Numpad3 = 40,
		[ScriptExportField("To be documented.")]
        Numpad4 = 41,
		[ScriptExportField("To be documented.")]
        Numpad5 = 42,
		[ScriptExportField("To be documented.")]
        Numpad6 = 43,
		[ScriptExportField("To be documented.")]
        Numpad7 = 44,
		[ScriptExportField("To be documented.")]
        Numpad8 = 45,
		[ScriptExportField("To be documented.")]
        Numpad9 = 46,
		[ScriptExportField("To be documented.")]
        NumpadPlus = 47,
		[ScriptExportField("To be documented.")]
        NumpadMinus = 48,
		[ScriptExportField("To be documented.")]
        NumpadDiv = 49,
		[ScriptExportField("To be documented.")]
        NumpadMult = 50,
		[ScriptExportField("To be documented.")]
        NumpadPeriod = 51,
		[ScriptExportField("To be documented.")]
        NumpadEnter = 52,
		[ScriptExportField("To be documented.")]
        Return = 53,
		[ScriptExportField("To be documented.")]
        Escape = 54,
		[ScriptExportField("To be documented.")]
        Backspace = 55,
		[ScriptExportField("To be documented.")]
        Tab = 56,
		[ScriptExportField("To be documented.")]
        Space = 57,
		[ScriptExportField("To be documented.")]
        Minus = 58,
		[ScriptExportField("To be documented.")]
        EqualsKey = 59,
		[ScriptExportField("To be documented.")]
        LeftBracket = 60,
		[ScriptExportField("To be documented.")]
        RightBracket = 61,
		[ScriptExportField("To be documented.")]
        Backslash = 62,
		[ScriptExportField("To be documented.")]
        InternationalHash = 63,
		[ScriptExportField("To be documented.")]
        Semicolon = 64,
		[ScriptExportField("To be documented.")]
        Apostrophe = 65,
		[ScriptExportField("To be documented.")]
        Grave = 66,
		[ScriptExportField("To be documented.")]
        Comma = 67,
		[ScriptExportField("To be documented.")]
        Period = 68,
		[ScriptExportField("To be documented.")]
        Slash = 69,
		[ScriptExportField("To be documented.")]
        Capslock = 70,
		[ScriptExportField("To be documented.")]
        F1 = 71,
		[ScriptExportField("To be documented.")]
        F2 = 72,
		[ScriptExportField("To be documented.")]
        F3 = 73,
		[ScriptExportField("To be documented.")]
        F4 = 74,
		[ScriptExportField("To be documented.")]
        F5 = 75,
		[ScriptExportField("To be documented.")]
        F6 = 76,
		[ScriptExportField("To be documented.")]
        F7 = 77,
		[ScriptExportField("To be documented.")]
        F8 = 78,
		[ScriptExportField("To be documented.")]
        F9 = 79,
		[ScriptExportField("To be documented.")]
        F10 = 80,
		[ScriptExportField("To be documented.")]
        F11 = 81,
		[ScriptExportField("To be documented.")]
        F12 = 82,
		[ScriptExportField("To be documented.")]
        F13 = 83,
		[ScriptExportField("To be documented.")]
        F14 = 84,
		[ScriptExportField("To be documented.")]
        F15 = 85,
		[ScriptExportField("To be documented.")]
        F16 = 86,
		[ScriptExportField("To be documented.")]
        F17 = 87,
		[ScriptExportField("To be documented.")]
        F18 = 88,
		[ScriptExportField("To be documented.")]
        F19 = 89,
		[ScriptExportField("To be documented.")]
        F20 = 90,
		[ScriptExportField("To be documented.")]
        F21 = 91,
		[ScriptExportField("To be documented.")]
        F22 = 92,
		[ScriptExportField("To be documented.")]
        F23 = 93,
		[ScriptExportField("To be documented.")]
        F24 = 94,
		[ScriptExportField("To be documented.")]
        PrintScreen = 95,
		[ScriptExportField("To be documented.")]
        ScrollLock = 96,
		[ScriptExportField("To be documented.")]
        Pause = 97,
		[ScriptExportField("To be documented.")]
        Insert = 98,
		[ScriptExportField("To be documented.")]
        Home = 99,
		[ScriptExportField("To be documented.")]
        PageUp = 100,
		[ScriptExportField("To be documented.")]
        Delete = 101,
		[ScriptExportField("To be documented.")]
        End = 102,
		[ScriptExportField("To be documented.")]
        PageDown = 103,
		[ScriptExportField("To be documented.")]
        ArrowRight = 104,
		[ScriptExportField("To be documented.")]
        ArrowLeft = 105,
		[ScriptExportField("To be documented.")]
        ArrowDown = 106,
		[ScriptExportField("To be documented.")]
        ArrowUp = 107,
		[ScriptExportField("To be documented.")]
        NumLock = 108,
		[ScriptExportField("To be documented.")]
        InternationalBackslash = 109,
		[ScriptExportField("To be documented.")]
        MediaApplication = 110,
		[ScriptExportField("To be documented.")]
        MediaPower = 111,
		[ScriptExportField("To be documented.")]
        NumpadEquals = 112,
		[ScriptExportField("To be documented.")]
        MediaExecute = 113,
		[ScriptExportField("To be documented.")]
        MediaHelp = 114,
		[ScriptExportField("To be documented.")]
        Menu = 115,
		[ScriptExportField("To be documented.")]
        MediaSelect = 116,
		[ScriptExportField("To be documented.")]
        MediaStop = 117,
		[ScriptExportField("To be documented.")]
        MediaAgain = 118,
		[ScriptExportField("To be documented.")]
        MediaUndo = 119,
		[ScriptExportField("To be documented.")]
        MediaCut = 120,
		[ScriptExportField("To be documented.")]
        MediaCopy = 121,
		[ScriptExportField("To be documented.")]
        MediaPaste = 122,
		[ScriptExportField("To be documented.")]
        MediaFind = 123,
		[ScriptExportField("To be documented.")]
        MediaMute = 124,
		[ScriptExportField("To be documented.")]
        MediaVolumeUp = 125,
		[ScriptExportField("To be documented.")]
        MediaVolumeDown = 126,
		[ScriptExportField("To be documented.")]
        International1 = 127,
		[ScriptExportField("To be documented.")]
        International2 = 128,
		[ScriptExportField("To be documented.")]
        International3 = 129,
		[ScriptExportField("To be documented.")]
        International4 = 130,
		[ScriptExportField("To be documented.")]
        International5 = 131,
		[ScriptExportField("To be documented.")]
        International6 = 132,
		[ScriptExportField("To be documented.")]
        International7 = 133,
		[ScriptExportField("To be documented.")]
        International8 = 134,
		[ScriptExportField("To be documented.")]
        International9 = 135,
		[ScriptExportField("To be documented.")]
        Colon = 136,
		[ScriptExportField("To be documented.")]
        CurrencySymbol = 137,
		[ScriptExportField("To be documented.")]
        CurrencySubSymbol = 138,
		[ScriptExportField("To be documented.")]
        LeftControl = 139,
		[ScriptExportField("To be documented.")]
        LeftShift = 140,
		[ScriptExportField("To be documented.")]
        LeftAlt = 141,
		[ScriptExportField("To be documented.")]
        LeftOsKey = 142,
		[ScriptExportField("To be documented.")]
        RightControl = 143,
		[ScriptExportField("To be documented.")]
        RightShift = 144,
		[ScriptExportField("To be documented.")]
        RightAlt = 145,
		[ScriptExportField("To be documented.")]
        RightOsKey = 146,
		[ScriptExportField("To be documented.")]
        Mode = 147,
		[ScriptExportField("To be documented.")]
        MediaNext = 148,
		[ScriptExportField("To be documented.")]
        MediaPrev = 149,
		[ScriptExportField("To be documented.")]
        MediaPlay = 150,
		[ScriptExportField("To be documented.")]
        MediaWeb = 151,
		[ScriptExportField("To be documented.")]
        MediaMail = 152,
		[ScriptExportField("To be documented.")]
        MediaCalculator = 153,
		[ScriptExportField("To be documented.")]
        MediaComputer = 154
    }
}